//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapWebService.Common
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/SRM/Basis/Global")]
    public partial class StandardMessageFault
    {
        
        private ExchangeFaultData standardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard
        {
            get
            {
                return this.standardField;
            }
            set
            {
                this.standardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.boschhuayu.com/wms")]
    public partial class ExchangeFaultData
    {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText
        {
            get
            {
                return this.faultTextField;
            }
            set
            {
                this.faultTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl
        {
            get
            {
                return this.faultUrlField;
            }
            set
            {
                this.faultUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail
        {
            get
            {
                return this.faultDetailField;
            }
            set
            {
                this.faultDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.boschhuayu.com/wms")]
    public partial class ExchangeLogData
    {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.boschhuayu.com/wms")]
    public partial class dt_wms_reserved_st
    {
        
        private string zRSV01Field;
        
        private string zRSV02Field;
        
        private string zRSV03Field;
        
        private string zRSV04Field;
        
        private string zRSV05Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZRSV01
        {
            get
            {
                return this.zRSV01Field;
            }
            set
            {
                this.zRSV01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZRSV02
        {
            get
            {
                return this.zRSV02Field;
            }
            set
            {
                this.zRSV02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZRSV03
        {
            get
            {
                return this.zRSV03Field;
            }
            set
            {
                this.zRSV03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZRSV04
        {
            get
            {
                return this.zRSV04Field;
            }
            set
            {
                this.zRSV04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZRSV05
        {
            get
            {
                return this.zRSV05Field;
            }
            set
            {
                this.zRSV05Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.boschhuayu.com/wms", ConfigurationName="SapWebService.Common.si_wms0007_outbound")]
    public interface si_wms0007_outbound
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SapWebService.Common.StandardMessageFault), Action="http://sap.com/xi/WebService/soap1.1", Name="StandardMessageFault", Namespace="http://sap.com/xi/SRM/Basis/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SapWebService.Common.si_wms0007_outboundResponse> si_wms0007_outboundAsync(SapWebService.Common.si_wms0007_outboundRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.boschhuayu.com/wms")]
    public partial class dt_wms0007_reqStockTransferc
    {
        
        private dt_wms0007_reqStockTransfercHeader headerField;
        
        private dt_wms0007_reqStockTransfercItems[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dt_wms0007_reqStockTransfercHeader header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public dt_wms0007_reqStockTransfercItems[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.boschhuayu.com/wms")]
    public partial class dt_wms0007_reqStockTransfercHeader
    {
        
        private string zWMSNUMBERField;
        
        private string zWMSNOField;
        
        private string zWMSDATEField;
        
        private string zWMSOPERATORField;
        
        private string zWMSTIMEField;
        
        private dt_wms_reserved_st reservedFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZWMSNUMBER
        {
            get
            {
                return this.zWMSNUMBERField;
            }
            set
            {
                this.zWMSNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZWMSNO
        {
            get
            {
                return this.zWMSNOField;
            }
            set
            {
                this.zWMSNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZWMSDATE
        {
            get
            {
                return this.zWMSDATEField;
            }
            set
            {
                this.zWMSDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZWMSOPERATOR
        {
            get
            {
                return this.zWMSOPERATORField;
            }
            set
            {
                this.zWMSOPERATORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZWMSTIME
        {
            get
            {
                return this.zWMSTIMEField;
            }
            set
            {
                this.zWMSTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public dt_wms_reserved_st reservedField
        {
            get
            {
                return this.reservedFieldField;
            }
            set
            {
                this.reservedFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.boschhuayu.com/wms")]
    public partial class dt_wms0007_reqStockTransfercItems
    {
        
        private string zWMSLINEField;
        
        private string mATNRField;
        
        private string mENGEField;
        
        private string wERKSField;
        
        private string lGORTField;
        
        private string iNSMKField;
        
        private string sOBKZField;
        
        private string lIFNRField;
        
        private string uMWRKField;
        
        private string uMLGOField;
        
        private string uMSOKField;
        
        private string eMLIFField;
        
        private string zsettlementField;
        
        private dt_wms0007_reqStockTransfercItemsHULIST[] hULISTField;
        
        private dt_wms_reserved_st reservedFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZWMSLINE
        {
            get
            {
                return this.zWMSLINEField;
            }
            set
            {
                this.zWMSLINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATNR
        {
            get
            {
                return this.mATNRField;
            }
            set
            {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MENGE
        {
            get
            {
                return this.mENGEField;
            }
            set
            {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string WERKS
        {
            get
            {
                return this.wERKSField;
            }
            set
            {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LGORT
        {
            get
            {
                return this.lGORTField;
            }
            set
            {
                this.lGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string INSMK
        {
            get
            {
                return this.iNSMKField;
            }
            set
            {
                this.iNSMKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SOBKZ
        {
            get
            {
                return this.sOBKZField;
            }
            set
            {
                this.sOBKZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string LIFNR
        {
            get
            {
                return this.lIFNRField;
            }
            set
            {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string UMWRK
        {
            get
            {
                return this.uMWRKField;
            }
            set
            {
                this.uMWRKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string UMLGO
        {
            get
            {
                return this.uMLGOField;
            }
            set
            {
                this.uMLGOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string UMSOK
        {
            get
            {
                return this.uMSOKField;
            }
            set
            {
                this.uMSOKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string EMLIF
        {
            get
            {
                return this.eMLIFField;
            }
            set
            {
                this.eMLIFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Zsettlement
        {
            get
            {
                return this.zsettlementField;
            }
            set
            {
                this.zsettlementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HULIST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public dt_wms0007_reqStockTransfercItemsHULIST[] HULIST
        {
            get
            {
                return this.hULISTField;
            }
            set
            {
                this.hULISTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public dt_wms_reserved_st reservedField
        {
            get
            {
                return this.reservedFieldField;
            }
            set
            {
                this.reservedFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.boschhuayu.com/wms")]
    public partial class dt_wms0007_reqStockTransfercItemsHULIST
    {
        
        private string eXIDVField;
        
        private string vEMNGField;
        
        private dt_wms_reserved_st reservedFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EXIDV
        {
            get
            {
                return this.eXIDVField;
            }
            set
            {
                this.eXIDVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VEMNG
        {
            get
            {
                return this.vEMNGField;
            }
            set
            {
                this.vEMNGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public dt_wms_reserved_st reservedField
        {
            get
            {
                return this.reservedFieldField;
            }
            set
            {
                this.reservedFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.boschhuayu.com/wms")]
    public partial class dt_wms0007_resResponseList
    {
        
        private string zWMSNUMBERField;
        
        private string zMESSAGEField;
        
        private string zDETIALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZWMSNUMBER
        {
            get
            {
                return this.zWMSNUMBERField;
            }
            set
            {
                this.zWMSNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZMESSAGE
        {
            get
            {
                return this.zMESSAGEField;
            }
            set
            {
                this.zMESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZDETIAL
        {
            get
            {
                return this.zDETIALField;
            }
            set
            {
                this.zDETIALField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class si_wms0007_outboundRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.boschhuayu.com/wms", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("StockTransferc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SapWebService.Common.dt_wms0007_reqStockTransferc[] mt_wms0007_req;
        
        public si_wms0007_outboundRequest()
        {
        }
        
        public si_wms0007_outboundRequest(SapWebService.Common.dt_wms0007_reqStockTransferc[] mt_wms0007_req)
        {
            this.mt_wms0007_req = mt_wms0007_req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class si_wms0007_outboundResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.boschhuayu.com/wms", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("responseList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SapWebService.Common.dt_wms0007_resResponseList[] mt_wms0007_res;
        
        public si_wms0007_outboundResponse()
        {
        }
        
        public si_wms0007_outboundResponse(SapWebService.Common.dt_wms0007_resResponseList[] mt_wms0007_res)
        {
            this.mt_wms0007_res = mt_wms0007_res;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface si_wms0007_outboundChannel : SapWebService.Common.si_wms0007_outbound, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class si_wms0007_outboundClient : System.ServiceModel.ClientBase<SapWebService.Common.si_wms0007_outbound>, SapWebService.Common.si_wms0007_outbound
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public si_wms0007_outboundClient(EndpointConfiguration endpointConfiguration) : 
                base(si_wms0007_outboundClient.GetBindingForEndpoint(endpointConfiguration), si_wms0007_outboundClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public si_wms0007_outboundClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(si_wms0007_outboundClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public si_wms0007_outboundClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(si_wms0007_outboundClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public si_wms0007_outboundClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SapWebService.Common.si_wms0007_outboundResponse> SapWebService.Common.si_wms0007_outbound.si_wms0007_outboundAsync(SapWebService.Common.si_wms0007_outboundRequest request)
        {
            return base.Channel.si_wms0007_outboundAsync(request);
        }
        
        public System.Threading.Tasks.Task<SapWebService.Common.si_wms0007_outboundResponse> si_wms0007_outboundAsync(SapWebService.Common.dt_wms0007_reqStockTransferc[] mt_wms0007_req)
        {
            SapWebService.Common.si_wms0007_outboundRequest inValue = new SapWebService.Common.si_wms0007_outboundRequest();
            inValue.mt_wms0007_req = mt_wms0007_req;
            return ((SapWebService.Common.si_wms0007_outbound)(this)).si_wms0007_outboundAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                //result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://poqas:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_WMS" +
                        "_QAS&receiverParty=&receiverService=&interface=si_wms0007_outbound&interfaceName" +
                        "space=http%3A%2F%2Fwww.boschhuayu.com%2Fwms");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://poqas:50001/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_WM" +
                        "S_QAS&receiverParty=&receiverService=&interface=si_wms0007_outbound&interfaceNam" +
                        "espace=http%3A%2F%2Fwww.boschhuayu.com%2Fwms");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
